### ISSUE TITLE
geocoding search bar operation and placement

### ISSUE THREAD

**Issue by terratenney** [terratenney/grasslander#1]

**Comment by cplouffe** [comment]
Works now, but I'm not sure if I agree about placement.  We could make it open by default?  Thoughts?

**Comment by terratenney** [comment]
It was open by default lets leave it open by default. But not sure what 
you mean by placement? On the server? In the code? In the grouped layers 
control?


On 6/11/2016 9:04 PM, Cameron Plouffe wrote:
>
> Works now, but I'm not sure if I agree about placement. We could make 
> it open by default? Thoughts?
>

-- 
Matthew Tenney
Ph.D. Candidate
Department of Geography
McGill University,
Montreal, QC, Canada

WGS84 (Lat/Long): 45.504698,-73.574901

e. matthew.tenney@mail.mcgill.ca
p. 514.975.8333
w. www.code-engage.com/home
t. @geothinkca

**Comment by cplouffe** [comment]
Open by default in my version now. I don't know what I mean by placement :)  It was in the title of the issue.

**Comment by terratenney** [comment]
AHHH geocoder !!!


yeah see its confusing reading the github lists emails. I thought you 
were doing the baselayer (grasslandbase)...


On 6/11/2016 9:13 PM, Cameron Plouffe wrote:
>
> Open by default in my version now. I don't know what I mean by 
> placement :) It was in the title of the issue.
>

-- 
Matthew Tenney
Ph.D. Candidate
Department of Geography
McGill University,
Montreal, QC, Canada

WGS84 (Lat/Long): 45.504698,-73.574901

e. matthew.tenney@mail.mcgill.ca
p. 514.975.8333
w. www.code-engage.com/home
t. @geothinkca

**Comment by terratenney** [comment]
Placement suggestion was by Brent: "Have a dialogue box that comes up (i.e., a preemptive modal in step 1 before click parcel instructions) that users must then enter their address to find their farm". Can be done later if working, but not working and in the same place - I don't think will cut it.
