### ISSUE TITLE
baselayers not working. 

### ISSUE THREAD

**Issue by terratenney** [terratenney/grasslander#12]

**Comment by colinr23** [comment]
the version i pulled from github reference the secure services (on 6443) - but they seem to be gone now. so all the layers dont draw -- tried replacing with http and 6080 but didnt work. maybe using a web adaptor now? or maybe i have an out of date version

**Comment by terratenney** [comment]
tagged Cam on it - as when he altered the way layer authentication was working - it seemed to have broken to the baselayers. One option was to move the grasslandbase folder outside of the grasslander folder (seemingly the easiest and can do once if no one else gets to it) or run the layers through the same user authentication process as the rest of them. I think its that simple anyways. I will manually set the initial map view to a wider zoom (encompassing the studey area polygon) in the meantime.

**Comment by cplouffe** [comment]
Hey guys,

I'll change it now.  There was no server-sde authentication going on at all
before, so securing services caused the basemaps to stop working.  I think
what Matt is suggesting is a good idea - move the services to a new folder
on the server named grasslander_public.

If it is any of the other layers, not sure why you are encountering issues
Colin.

I will put a bit of time into this now, and I will probably be able to
spend a little bit of time tomorrow

Cam

**Comment by colinr23** [comment]
this will fix aafc layer 

var aafc_inventory = L.tileLayer.wms('http://www.agr.gc.ca/atlas/services/imageservices/aafc_crop_inventory_2014_30m/ImageServer/WMSServer?', {

**Comment by terratenney** [comment]
Cam can you fix the field create and field activities layers to fit your 
afternoons rewiring. I just realized Ive been writing an update function 
for something that doesn't work.


On 6/11/2016 9:05 PM, colinr23 wrote:
>
> this will fix aafc layer
>
> var aafc_inventory = 
> L.tileLayer.wms('http://www.agr.gc.ca/atlas/services/imageservices/aafc_crop_inventory_2014_30m/ImageServer/WMSServer?', 
> {
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/terratenney/grasslander/issues/12#issuecomment-225403266>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AGnNXckhEwdEPe5hNaGeeuOLrbnN3_RAks5qK1tngaJpZM4IzqLZ>.
>

-- 
Matthew Tenney
Ph.D. Candidate
Department of Geography
McGill University,
Montreal, QC, Canada

WGS84 (Lat/Long): 45.504698,-73.574901

e. matthew.tenney@mail.mcgill.ca
p. 514.975.8333
w. www.code-engage.com/home
t. @geothinkca

**Comment by colinr23** [comment]
i was referring to the ebird and NHIC data - which are referencing 6443 / https but the grasslander folder in https://www.grasslander.org:6443/arcgis/rest/ is no longer there.. so i think they've already been moved, just need to update the app1.js baseurl variable.. and i guess have two baseurl - one for secured and one for not

**Comment by cplouffe** [comment]
Exactly. I think that is the most logical solution.

**Comment by colinr23** [comment]
this still needs to be done. current version on the site is broken so am not going to pull the latest code. getting on a plane now
