### ISSUE TITLE
add zoom-to-farm button

### ISSUE THREAD

**Issue by colinr23** [terratenney/grasslander#14]
but unlock whatever zoom locks you have now, -- if a user has multiple farms in different areas - they cant zoom into detail into either (or this was the case for me).. vast majority will have one farm poly. could even limit it to this if it makes it easier

**Comment by terratenney** [comment]
Added zoom to full extent button. Added zoom to ALL FARM bounds in farm setup stage. Removed automatic zoom to farm in subsequent stage due to previous request.
